city: praha
start: 2017-05-17 19:00:00
name: Pražské PyVo
number: 74
topic: Serverless
description: |

    Milé pyvařky a pyvaři,

    stejně jako každou 3. středu v měsíci, i nyní se koná Python sraz v Praze.

    Dozvíte se, jak využít cloudové platformy typu Google Cloud, AWS, Heroku
    i jiný hosting k běhu vašich malých aplikací tak, abyste nemuseli administrovat žádný
    (ani virtuální) server.

    Formát bude tentokrát jenom lightning talkový, tj. pro každého 5 minut o zkušenostech bez serveru.

venue: na-venecku
talks:

- title: Statický blog v Pelicanu na GitHub Pages
  speakers:
  - Honza Javorek
  urls: []
  coverage: []

- title: Statické webové stránky ve Flasku na GitHub Pages
  speakers:
  - Miro Hrončok
  urls:
  - https://github.com/hroncok/elsa_prague_pyvo

#- title: now JS  # psal na Slacku, ze to asi nestiha
#  speakers:
#  - Roman Krejčík

- title: now Docker + Python
  speakers:
  - Petr Messner
  urls: []
  coverage: []

- title: AWS Lambda
  speakers:
  - Jiří

- title: Roští
  speakers:
  - Martin

- title: ??
  description: |
    I ty můžeš přednášet! :)
    viz [pyvo.cz#info-for-speakers](https://pyvo.cz/#info-for-speakers)

urls: []
